version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local

services:

  app:
    build:
      context: .
    container_name: topic-board
    networks:
      - app-network
    depends_on:
      - postgres-db
    env_file:
      - .env
    ports:
      - '8085:8080'

  postgres-db:
    image: postgres:latest
    container_name: topic-board-db
    env_file:
      - .env
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
