spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}?stringtype=unspecified
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
server:
  port: 8085
security:
  jwt:
    secret: ${JWT_SECRET}
    access: ${JWT_ACCESS_DURATION}
    refresh: ${JWT_REFRESH_DURATION}

