spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5435/topic-board?stringtype=unspecified
    username: topic-board
    password: topic-board
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
server:
  port: 8085

security:
  jwt:
    secret: enhnaGNmamJ4d2JhYmV3YmhjZWJqaGVzcnZrcnNlaGNyYmx3aGJjcmhiY2tzaGJjd2JocmVsYmFjcmhiZWthY2hy
    access: 10m
    refresh: 1h

